version:     "0009--09-Oct-2022"
copyright:   "2022"
author:      "Virtual Ass"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/vrtass/os222/"
myloglink:   "/TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
